import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const formPath = new URL('../src/features/account/AccountProfileForm.tsx', import.meta.url)
const comboboxPath = new URL('../src/features/account/ProfileCombobox.tsx', import.meta.url)
const comboboxStylesPath = new URL('../src/features/account/profile-combobox.module.css', import.meta.url)
const pagePath = new URL('../src/app/(account)/cuenta/perfil/page.tsx', import.meta.url)
const stylesPath = new URL('../src/features/account/account-profile.module.css', import.meta.url)
const modernStylesPath = new URL('../src/features/account/account-profile-modern.module.css', import.meta.url)
const servicePath = new URL('../src/features/account/services/account-service.ts', import.meta.url)
const migrationPath = new URL('../supabase/migrations/20260804143000_profile_avatars_storage.sql', import.meta.url)
async function read(path) { return readFile(path, 'utf8') }

test('profile workspace exposes progress actionable checklist and avatar shortcut', async () => {
  const [form, page] = await Promise.all([read(formPath), read(pagePath)])
  assert.match(page, /<AccountProfileForm profile=\{profile\}/)
  assert.match(form, /profile-identity-title/)
  assert.match(form, /profile-completion-title/)
  assert.match(form, /Perfil completado al/)
  assert.match(form, /Editar fotografía/)
  assert.match(form, /completionFields\.map/)
  assert.match(form, /href=\{field\.target\}/)
  assert.match(form, /Completar →/)
  assert.match(form, /La vinculación con una ficha eclesial es opcional/)
})

test('profile state is normalized and never reports initial changes', async () => {
  const form = await read(formPath)
  assert.match(form, /function normalizeValue/)
  assert.match(form, /function normalizeForm/)
  assert.match(form, /const \[baseline,\s*setBaseline\]/)
  assert.match(form, /JSON\.stringify\(normalizedForm\)\s*!==\s*JSON\.stringify\(normalizeForm\(baseline\)\)/)
  assert.match(form, /setBaseline\(saved\)/)
  assert.match(form, /\(isDirty\s*\|\|\s*saving\)\s*\?/)
})

test('profile success feedback is temporary and accessible', async () => {
  const form = await read(formPath)
  assert.match(form, /window\.setTimeout\(\(\)\s*=>\s*setMessage\(null\),\s*4000\)/)
  assert.match(form, /aria-live="polite"/)
  assert.match(form, /role="status"/)
  assert.match(form, /Tu perfil fue actualizado correctamente/)
})

test('profile avatar uses visible selection, optimization and observable upload stages', async () => {
  const [form, service, migration] = await Promise.all([read(formPath), read(servicePath), read(migrationPath)])
  assert.match(form, /accept="image\/jpeg,image\/png,image\/webp"/)
  assert.match(form, /className=\{modernStyles\.fileChooser\}/)
  assert.match(form, /type="file"/)
  assert.match(form, /input\.files\?\.\[0\]/)
  assert.match(form, /input\.value = ''/)
  assert.match(form, /avatarFileName/)
  assert.match(form, /optimizeProfileAvatar/)
  assert.match(form, /setAvatarStage\('preparing'\)/)
  assert.match(form, /setAvatarStage\('uploading'\)/)
  assert.match(form, /setAvatarStage\('saving'\)/)
  assert.match(form, /modernStyles\.uploadStatus/)
  assert.match(form, /modernStyles\.uploadError/)
  assert.match(form, /uploadMyProfileAvatar/)
  assert.match(form, /saveMyAccountProfile\(supabase,\s*\{\s*\.\.\.normalizedForm,\s*avatarUrl:\s*uploadedUrl\s*\}\)/s)
  assert.match(form, /Tu fotografía fue actualizada correctamente/)
  assert.match(form, /Hasta 20 MB; las imágenes grandes se optimizan automáticamente/)
  assert.doesNotMatch(form, /URL de la fotografía/)
  assert.match(service, /MAX_AVATAR_BYTES = 5 \* 1024 \* 1024/)
  assert.match(service, /MAX_SOURCE_AVATAR_BYTES = 20 \* 1024 \* 1024/)
  assert.match(service, /export async function optimizeProfileAvatar/)
  assert.match(service, /createImageBitmap/)
  assert.match(service, /canvasToBlob/)
  assert.match(service, /No se pudo subir la fotografía:/)
  assert.match(service, /storage\.from\(AVATAR_BUCKET\)\.getPublicUrl/)
  assert.match(migration, /insert into storage\.buckets/)
  assert.match(migration, /file_size_limit/)
  assert.match(migration, /storage\.foldername\(name\)/)
  assert.match(migration, /auth\.uid\(\)::text/)
})

test('profile protected email is rendered as data rather than disabled input', async () => {
  const form = await read(formPath)
  assert.match(form, /styles\.protectedField/)
  assert.match(form, /styles\.protectedBadge/)
  assert.match(form, /styles\.protectedValue/)
  assert.match(form, /<LockIcon\s*\/>Protegido/)
  assert.doesNotMatch(form, /<input disabled type="email"/)
})

test('profile controls and avatar resist global element overrides', async () => {
  const [styles, modernStyles] = await Promise.all([read(stylesPath), read(modernStylesPath)])
  assert.match(styles, /\.protectedBadge>\.lockIcon\{[^}]*width:14px!important/s)
  assert.match(styles, /\.checklist\{[^}]*display:grid!important/s)
  assert.match(styles, /\.dataCard\{[^}]*display:grid!important/s)
  assert.match(modernStyles, /\.avatarSurface\{[^}]*width:112px!important/s)
  assert.match(modernStyles, /\.photoSurface\{[^}]*border-radius:50%!important/s)
  assert.match(modernStyles, /\.uploadPanel\{[^}]*position:relative!important/s)
  assert.match(modernStyles, /\.uploadPanel::before\{[^}]*content:'Seleccionar fotografía'/s)
  assert.match(modernStyles, /\.fileChooser\{[^}]*position:absolute!important/s)
  assert.match(modernStyles, /\.fileChooser\{[^}]*opacity:0!important/s)
  assert.match(modernStyles, /\.uploadStatus,\.uploadError\{[^}]*display:flex!important/s)
})

test('profile preferences use accessible custom comboboxes instead of native selects', async () => {
  const [form, combobox, comboboxStyles] = await Promise.all([read(formPath), read(comboboxPath), read(comboboxStylesPath)])
  assert.match(form, /import ProfileCombobox/)
  assert.match(form, /LOCALE_OPTIONS/)
  assert.match(form, /TIMEZONE_OPTIONS/)
  assert.match(form, /id="profile-locale"/)
  assert.match(form, /id="profile-timezone"/)
  assert.match(form, /searchable/)
  assert.match(form, /Buscar ciudad o zona horaria/)
  assert.doesNotMatch(form, /<select/)
  assert.doesNotMatch(form, /<datalist/)
  assert.match(combobox, /aria-haspopup="listbox"/)
  assert.match(combobox, /aria-expanded=\{open\}/)
  assert.match(combobox, /role="listbox"/)
  assert.match(combobox, /role="option"/)
  assert.match(combobox, /aria-selected=\{selected\}/)
  assert.match(combobox, /event\.key === 'Escape'/)
  assert.match(combobox, /event\.key === 'ArrowDown'/)
  assert.match(combobox, /event\.key === 'ArrowUp'/)
  assert.match(comboboxStyles, /\.popover\{[^}]*position:absolute!important/s)
  assert.match(comboboxStyles, /@media\(max-width:700px\)/)
  assert.doesNotMatch(comboboxStyles, /#[0-9a-f]{3,8}/i)
})

test('profile presentation includes progress toast responsive rules and semantic surfaces', async () => {
  const [styles, modernStyles] = await Promise.all([read(stylesPath), read(modernStylesPath)])
  assert.match(styles, /\.identityProgress/)
  assert.match(styles, /\.progressTrack/)
  assert.match(styles, /\.checkPending/)
  assert.match(styles, /\.toast\{[^}]*position:fixed/s)
  assert.match(styles, /bottom:calc\(7\.25rem \+ env\(safe-area-inset-bottom\)\)/)
  assert.match(styles, /var\(--surface-primary\)/)
  assert.match(styles, /var\(--text-primary\)/)
  assert.match(styles, /var\(--focus-ring\)/)
  assert.match(modernStyles, /@media\(max-width:800px\)/)
  assert.match(modernStyles, /@media\(max-width:520px\)/)
  assert.match(modernStyles, /@media\(prefers-reduced-motion:reduce\)/)
})
