import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const formPath = new URL('../src/features/account/AccountProfileForm.tsx', import.meta.url)
const pagePath = new URL('../src/app/(account)/cuenta/perfil/page.tsx', import.meta.url)
const stylesPath = new URL('../src/features/account/account-profile.module.css', import.meta.url)
const modernStylesPath = new URL('../src/features/account/account-profile-modern.module.css', import.meta.url)
const servicePath = new URL('../src/features/account/services/account-service.ts', import.meta.url)
const migrationPath = new URL('../supabase/migrations/20260804143000_profile_avatars_storage.sql', import.meta.url)
async function read(path) { return readFile(path, 'utf8') }

test('profile workspace exposes progress actionable checklist and avatar shortcut', async () => {
  const [form, page] = await Promise.all([read(formPath), read(pagePath)])
  assert.match(page, /<AccountProfileForm profile=\{profile\}/)
  assert.match(form, /profile-identity-title/)
  assert.match(form, /profile-completion-title/)
  assert.match(form, /Perfil completado al/)
  assert.match(form, /Editar fotografía/)
  assert.match(form, /completionFields\.map/)
  assert.match(form, /href=\{field\.target\}/)
  assert.match(form, /Completar →/)
  assert.match(form, /La vinculación con una ficha eclesial es opcional/)
})

test('profile state is normalized and never reports initial changes', async () => {
  const form = await read(formPath)
  assert.match(form, /function normalizeValue/)
  assert.match(form, /function normalizeForm/)
  assert.match(form, /const \[baseline,\s*setBaseline\]/)
  assert.match(form, /JSON\.stringify\(normalizedForm\)\s*!==\s*JSON\.stringify\(normalizeForm\(baseline\)\)/)
  assert.match(form, /setBaseline\(saved\)/)
  assert.match(form, /\(isDirty\s*\|\|\s*saving\)\s*\?/)
})

test('profile success feedback is temporary and accessible', async () => {
  const form = await read(formPath)
  assert.match(form, /window\.setTimeout\(\(\)\s*=>\s*setMessage\(null\),\s*4000\)/)
  assert.match(form, /aria-live="polite"/)
  assert.match(form, /role="status"/)
  assert.match(form, /Tu perfil fue actualizado correctamente/)
})

test('profile avatar uses direct observable storage upload instead of external url input', async () => {
  const [form, service, migration] = await Promise.all([read(formPath), read(servicePath), read(migrationPath)])
  assert.match(form, /accept="image\/jpeg,image\/png,image\/webp"/)
  assert.match(form, /type="file"/)
  assert.match(form, /htmlFor="profile-photo-input"/)
  assert.match(form, /void handleAvatarSelection\(event\.target\.files\?\.\[0\]\)/)
  assert.match(form, /const \[avatarSaving,\s*setAvatarSaving\]/)
  assert.match(form, /uploadMyProfileAvatar/)
  assert.match(form, /saveMyAccountProfile\(supabase,\s*\{\s*\.\.\.normalizedForm,\s*avatarUrl:\s*uploadedUrl\s*\}\)/s)
  assert.match(form, /El cambio se guarda automáticamente/)
  assert.match(form, /Tu fotografía fue actualizada correctamente/)
  assert.match(form, /removeMyProfileAvatar/)
  assert.match(form, /JPG, PNG o WEBP\. Máximo 5 MB/)
  assert.doesNotMatch(form, /URL de la fotografía/)
  assert.match(service, /AVATAR_BUCKET = 'profile-avatars'/)
  assert.match(service, /MAX_AVATAR_BYTES = 5 \* 1024 \* 1024/)
  assert.match(service, /storage\.from\(AVATAR_BUCKET\)\.getPublicUrl/)
  assert.match(migration, /insert into storage\.buckets/)
  assert.match(migration, /file_size_limit/)
  assert.match(migration, /storage\.foldername\(name\)/)
  assert.match(migration, /auth\.uid\(\)::text/)
})

test('profile protected email is rendered as data rather than disabled input', async () => {
  const form = await read(formPath)
  assert.match(form, /styles\.protectedField/)
  assert.match(form, /styles\.protectedBadge/)
  assert.match(form, /styles\.protectedValue/)
  assert.match(form, /<LockIcon\s*\/>Protegido/)
  assert.doesNotMatch(form, /<input disabled type="email"/)
})

test('profile controls and avatar resist global element overrides', async () => {
  const [styles, modernStyles] = await Promise.all([read(stylesPath), read(modernStylesPath)])
  assert.match(styles, /\.protectedBadge>\.lockIcon\{[^}]*width:14px!important/s)
  assert.match(styles, /\.checklist\{[^}]*display:grid!important/s)
  assert.match(styles, /\.dataCard\{[^}]*display:grid!important/s)
  assert.match(modernStyles, /\.controlSurface\{[^}]*appearance:none!important/s)
  assert.match(modernStyles, /\.avatarSurface\{[^}]*width:94px!important/s)
  assert.match(modernStyles, /\.uploadPanel\{[^}]*display:flex!important/s)
  assert.match(modernStyles, /\.uploadButton\{[^}]*background:var\(--brand-primary\)!important/s)
  assert.match(modernStyles, /\.fileInput\{[^}]*clip:rect/s)
})

test('profile preferences use controlled locale and timezone selects', async () => {
  const form = await read(formPath)
  assert.match(form, /TIMEZONE_OPTIONS/)
  assert.match(form, /id="profile-timezone"/)
  assert.match(form, /TIMEZONE_OPTIONS\.map/)
  assert.match(form, /America\/Santo_Domingo/)
  assert.match(form, /value=\{form\.preferredLocale\}/)
  assert.match(form, /value=\{form\.timezone\}/)
  assert.doesNotMatch(form, /<datalist/)
})

test('profile presentation includes progress toast and responsive rules', async () => {
  const [styles, modernStyles] = await Promise.all([read(stylesPath), read(modernStylesPath)])
  assert.match(styles, /\.identityProgress/)
  assert.match(styles, /\.progressTrack/)
  assert.match(styles, /\.checkPending/)
  assert.match(styles, /\.toast\{[^}]*position:fixed/s)
  assert.match(styles, /bottom:calc\(7\.25rem \+ env\(safe-area-inset-bottom\)\)/)
  assert.match(modernStyles, /@media\(max-width:800px\)/)
  assert.match(modernStyles, /@media\(max-width:520px\)/)
  assert.match(modernStyles, /@media\(prefers-reduced-motion:reduce\)/)
  assert.doesNotMatch(`${styles}\n${modernStyles}`, /#[0-9a-f]{3,8}/i)
})
